{
  "openapi": "3.0.3",
  "info": {
    "title": "PagerDuty Slack Integration API",
    "version": "1.0.0",
    "contact": {
      "name": "PagerDuty Support",
      "url": "http://www.pagerduty.com/support",
      "email": "support@pagerduty.com"
    },
    "description": "This is API documentation for PagerDuty's integration with Slack.\n\nTo begin the integration, you will need to map your PagerDuty account to your Slack Workspace.\nAfter configuring an Extension on each Service, Incident notifications will be posted in the configured Slack channel.\n\nAdditional integration documentation can be found here: https://support.pagerduty.com/docs/slack-integration-guide.\n\n> ### Important\n>\n>  Ensure you are using a User API Token to make requests to this API. Also, check that your user has necessary\n>  permissions (Owner or Global Admin). See https://developer.pagerduty.com/docs/rest-api-v2/authentication/ for the\n>  details."
  },
  "servers": [
    {
      "url": "https://api.pagerduty.com/integration-slack"
    }
  ],
  "tags": [
    {
      "name": "Slack Connections",
      "description": "Slack Connections are used to create mappings between Slack channels and PagerDuty Services and Teams."
    },
    {
      "name": "Slack Dedicated Channels",
      "description": "Incident dedicated channels are created so that everything related to the incident can be handled in one slack channel."
    },
    {
      "name": "Slack Notification Channels",
      "description": "Incident notification channels are slack channels linked to send non-critical notifications of the incident."
    }
  ],
  "security": [
    {
      "apiKey": []
    },
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/incidents/{incident_id}/dedicated_channel": {
      "parameters": [
        {
          "$ref": "#/components/parameters/incident_id"
        }
      ],
      "get": {
        "summary": "Get a Slack Dedicated Channel",
        "operationId": "getDedicatedChannel",
        "description": "Returns an incident's slack dedicated channel.",
        "parameters": [
          {
            "$ref": "#/components/parameters/incident_id"
          }
        ],
        "tags": [
          "Slack Dedicated Channels"
        ],
        "responses": {
          "200": {
            "description": "The incident slack dedicated channel.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "channel": {
                      "$ref": "#/components/schemas/SlackChannel"
                    }
                  },
                  "required": [
                    "channel"
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "channel": {
                        "id": "C0123456789",
                        "name": "dedicated",
                        "slack_team_id": "T0123456789",
                        "link": "https://slack.com/app_redirect?channel=C0123456789&team=T0123456789",
                        "deep_link": "slack://channel?team=T0123456789&id=C0123456789"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      },
      "post": {
        "tags": [
          "Slack Dedicated Channels"
        ],
        "summary": "Create a Slack Dedicated Channel",
        "description": "Creates an incident's slack dedicated channel.",
        "operationId": "createDedicatedChannel",
        "parameters": [
          {
            "$ref": "#/components/parameters/incident_id"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "channel": {
                    "$ref": "#/components/schemas/CreateDedicatedChannelPayload"
                  }
                },
                "required": [
                  "channel"
                ]
              },
              "examples": {
                "Request": {
                  "summary": "Request Example",
                  "value": {
                    "channel": {
                      "name": "dedicated",
                      "privacy": "public",
                      "slack_team_id": "T0123456789"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Returns created Slack Dedicated Channel.",
            "headers": {
              "Location": {
                "schema": {
                  "type": "string"
                },
                "description": "The path to get the new incident dedicated channel info"
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "channel": {
                      "$ref": "#/components/schemas/SlackChannel"
                    },
                    "warnings": {
                      "type": "array",
                      "description": "List of unblocking events that can possibly occur durring the channel creation.",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "channel"
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "channel": {
                        "id": "C0123456789",
                        "name": "dedicated",
                        "slack_team_id": "T0123456789",
                        "link": "https://slack.com/app_redirect?channel=C0123456789&team=T0123456789",
                        "deep_link": "slack://channel?team=T0123456789&id=C0123456789"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/UnprocessableEntity"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      },
      "delete": {
        "tags": [
          "Slack Dedicated Channels"
        ],
        "summary": "Remove a Slack Dedicated Channel",
        "description": "Removes an incident's slack dedicated channel.",
        "operationId": "removeDedicatedChannel",
        "parameters": [
          {
            "$ref": "#/components/parameters/incident_id"
          }
        ],
        "responses": {
          "204": {
            "description": "The incident slack dedicated channel was deleted successfully."
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/incidents/{incident_id}/notification_channels": {
      "parameters": [
        {
          "$ref": "#/components/parameters/incident_id"
        }
      ],
      "get": {
        "summary": "List Notification Channels",
        "operationId": "getNotificationChannels",
        "description": "Returns an incident's list of slack notification channels.",
        "parameters": [
          {
            "$ref": "#/components/parameters/incident_id"
          }
        ],
        "tags": [
          "Slack Notification Channels"
        ],
        "responses": {
          "200": {
            "description": "The incident's list of slack notification channels.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "channels": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/SlackChannel"
                      }
                    }
                  },
                  "required": [
                    "channels"
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "channels": [
                        {
                          "id": "C0123456789",
                          "name": "notification1",
                          "slack_team_id": "T0123456789",
                          "link": "https://slack.com/app_redirect?channel=C0123456789&team=T0123456789",
                          "deep_link": "slack://channel?team=T0123456789&id=C0123456789"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      },
      "post": {
        "tags": [
          "Slack Notification Channels"
        ],
        "summary": "Create a Slack Notification Channel",
        "description": "Creates an incident's slack notification channel.",
        "operationId": "createNotificationChannel",
        "parameters": [
          {
            "$ref": "#/components/parameters/incident_id"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "channel": {
                    "$ref": "#/components/schemas/CreateNotificationChannelPayload"
                  }
                },
                "required": [
                  "channel"
                ]
              },
              "examples": {
                "Request": {
                  "summary": "Request Example",
                  "value": {
                    "channel": {
                      "id": "C0123456789",
                      "slack_team_id": "T0123456789"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Returns linked Slack Notification Channel.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "channel": {
                      "$ref": "#/components/schemas/SlackChannel"
                    },
                    "warnings": {
                      "type": "array",
                      "description": "List of unblocking events that can possibly occur durring the channel linking process.",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "channel"
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "channel": {
                        "id": "C0123456789",
                        "name": "notification",
                        "slack_team_id": "T0123456789",
                        "link": "https://slack.com/app_redirect?channel=C0123456789&team=T0123456789",
                        "deep_link": "slack://channel?team=T0123456789&id=C0123456789"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/UnprocessableEntity"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      },
      "put": {
        "tags": [
          "Slack Notification Channels"
        ],
        "summary": "Update Slack Notification Channels",
        "description": "Update an incident's slack notification channels.",
        "operationId": "updateNotificationChannel",
        "parameters": [
          {
            "$ref": "#/components/parameters/incident_id"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "channels": {
                    "$ref": "#/components/schemas/UpdateNotificationChannelPayload"
                  }
                },
                "required": [
                  "channels"
                ]
              },
              "examples": {
                "Request": {
                  "summary": "Request Example",
                  "value": {
                    "channels": [
                      {
                        "id": "C0123456789",
                        "slack_team_id": "T0123456789"
                      },
                      {
                        "id": "C0987654321",
                        "slack_team_id": "T0987654321"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Returns the new list of Slack Notification Channel.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "channels": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/SlackChannel"
                      }
                    },
                    "warnings": {
                      "type": "array",
                      "description": "List of failed operations, when the success is only partial.",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "required": [
                    "channels"
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "channels": [
                        {
                          "id": "C0123456789",
                          "name": "notification1",
                          "slack_team_id": "T0123456789",
                          "link": "https://slack.com/app_redirect?channel=C0123456789&team=T0123456789",
                          "deep_link": "slack://channel?team=T0123456789&id=C0123456789"
                        },
                        {
                          "id": "C0987654321",
                          "name": "notification2",
                          "slack_team_id": "T0987654321",
                          "link": "https://slack.com/app_redirect?channel=C0987654321&team=T0987654321",
                          "deep_link": "slack://channel?team=T0987654321&id=C0987654321"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "422": {
            "$ref": "#/components/responses/UnprocessableEntity"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/incidents/{incident_id}/notification_channels/{channel_id}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/incident_id"
        },
        {
          "$ref": "#/components/parameters/channel_id"
        }
      ],
      "delete": {
        "tags": [
          "Slack Notification Channels"
        ],
        "summary": "Remove a Slack Notification Channel",
        "description": "Unlinks an incident's slack notification channel.",
        "operationId": "removeNotificationChannel",
        "parameters": [
          {
            "$ref": "#/components/parameters/incident_id"
          },
          {
            "$ref": "#/components/parameters/channel_id"
          }
        ],
        "responses": {
          "204": {
            "description": "The incident slack notification channel was unlinked successfully."
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/workspaces/{slack_team_id}/connections": {
      "parameters": [
        {
          "$ref": "#/components/parameters/slack_team_id"
        }
      ],
      "get": {
        "tags": [
          "Slack Connections"
        ],
        "servers": [
          {
            "url": "https://app.pagerduty.com/integration-slack"
          }
        ],
        "summary": "List Slack Connections",
        "description": "Returns a list of Slack Connections.",
        "operationId": "getConnections",
        "parameters": [
          {
            "$ref": "#/components/parameters/slack_team_id"
          },
          {
            "$ref": "#/components/parameters/limit"
          },
          {
            "$ref": "#/components/parameters/offset"
          }
        ],
        "responses": {
          "200": {
            "description": "A set of Slack Connections matching the request.",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "type": "object",
                      "properties": {
                        "slack_connections": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/SlackConnection"
                          }
                        }
                      },
                      "required": [
                        "slack_connections"
                      ]
                    },
                    {
                      "$ref": "#/components/schemas/Pagination"
                    }
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "slack_connections": [
                        {
                          "id": "A12BCDE",
                          "source_id": "A1234B5",
                          "source_name": "test_team",
                          "source_type": "team_reference",
                          "channel_id": "A123B456C7D",
                          "channel_name": "random",
                          "notification_type": "responder",
                          "config": {
                            "events": [
                              "incident.triggered",
                              "incident.acknowledged",
                              "incident.escalated",
                              "incident.resolved",
                              "incident.reassigned",
                              "incident.annotated",
                              "incident.unacknowledged",
                              "incident.delegated",
                              "incident.priority_updated",
                              "incident.responder.added",
                              "incident.responder.replied",
                              "incident.status_update_published"
                            ],
                            "priorities": [
                              "ABCDEF1",
                              "AB1CDE2"
                            ],
                            "urgency": null
                          }
                        }
                      ],
                      "limit": 1,
                      "offset": 0,
                      "more": true,
                      "total": 99
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      },
      "post": {
        "tags": [
          "Slack Connections"
        ],
        "servers": [
          {
            "url": "https://app.pagerduty.com/integration-slack"
          }
        ],
        "summary": "Create a Slack Connection",
        "description": "Creates a Slack Connection\n\n> ### Important\n>\n>  Make sure that your PagerDuty account is linked to your Slack workspace and your PagerDuty user is linked to your Slack user. You can do this on the Slack extension page in your PagerDuty account.\n",
        "operationId": "createConnection",
        "parameters": [
          {
            "$ref": "#/components/parameters/slack_team_id"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "slack_connection": {
                    "$ref": "#/components/schemas/SlackConnection"
                  }
                },
                "required": [
                  "slack_connection"
                ]
              },
              "examples": {
                "Request": {
                  "summary": "Request Example",
                  "value": {
                    "slack_connection": {
                      "source_id": "A1234B5",
                      "source_type": "team_reference",
                      "channel_id": "A123B456C7D",
                      "notification_type": "responder",
                      "config": {
                        "events": [
                          "incident.triggered",
                          "incident.acknowledged",
                          "incident.escalated",
                          "incident.resolved",
                          "incident.reassigned",
                          "incident.annotated",
                          "incident.unacknowledged",
                          "incident.delegated",
                          "incident.priority_updated",
                          "incident.responder.added",
                          "incident.responder.replied",
                          "incident.status_update_published"
                        ],
                        "priorities": [
                          "ABCDEF1",
                          "AB1CDE2"
                        ],
                        "urgency": null
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Returns created Slack Connection.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "slack_connection": {
                      "$ref": "#/components/schemas/SlackConnection"
                    }
                  },
                  "required": [
                    "slack_connection"
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "slack_connection": {
                        "id": "A12BCDE",
                        "source_id": "A1234B5",
                        "source_name": "test_team",
                        "source_type": "team_reference",
                        "channel_id": "A123B456C7D",
                        "channel_name": "random",
                        "notification_type": "responder",
                        "config": {
                          "events": [
                            "incident.triggered",
                            "incident.acknowledged",
                            "incident.escalated",
                            "incident.resolved",
                            "incident.reassigned",
                            "incident.annotated",
                            "incident.unacknowledged",
                            "incident.delegated",
                            "incident.priority_updated",
                            "incident.responder.added",
                            "incident.responder.replied",
                            "incident.status_update_published"
                          ],
                          "priorities": [
                            "ABCDEF1",
                            "AB1CDE2"
                          ],
                          "urgency": null
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Caller provided invalid arguments. Please review the response for error details. Retrying with the same arguments will *not* work.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "ValidationError": {
                    "summary": "Validation Error",
                    "value": {
                      "error": {
                        "errors": [
                          "Name can't be blank"
                        ],
                        "message": "Invalid Input Provided"
                      }
                    }
                  },
                  "InvalidInputProvided": {
                    "summary": "Invalid channel_id provided",
                    "value": {
                      "error": {
                        "message": "Unable to update a Slack Connection: Slack channel name fetch failed"
                      }
                    }
                  },
                  "MalformedJson": {
                    "summary": "Malformed JSON",
                    "value": {
                      "error": {
                        "message": "Malformed JSON"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      }
    },
    "/workspaces/{slack_team_id}/connections/{connection_id}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/slack_team_id"
        },
        {
          "$ref": "#/components/parameters/connection_id"
        }
      ],
      "get": {
        "summary": "Get a Slack Connection",
        "operationId": "getConnection",
        "description": "Get details about an existing Slack Connection.",
        "parameters": [
          {
            "$ref": "#/components/parameters/slack_team_id"
          },
          {
            "$ref": "#/components/parameters/connection_id"
          }
        ],
        "tags": [
          "Slack Connections"
        ],
        "servers": [
          {
            "url": "https://app.pagerduty.com/integration-slack"
          }
        ],
        "responses": {
          "200": {
            "description": "The Slack Connection requested.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "slack_connection": {
                      "$ref": "#/components/schemas/SlackConnection"
                    }
                  },
                  "required": [
                    "slack_connection"
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "slack_connection": {
                        "id": "A12BCDE",
                        "source_id": "A1234B5",
                        "source_name": "test_service",
                        "source_type": "service_reference",
                        "channel_id": "A123B456C7D",
                        "channel_name": "random",
                        "notification_type": "responder",
                        "config": {
                          "events": [
                            "incident.triggered",
                            "incident.acknowledged",
                            "incident.escalated",
                            "incident.resolved",
                            "incident.reassigned",
                            "incident.annotated",
                            "incident.unacknowledged",
                            "incident.delegated",
                            "incident.priority_updated",
                            "incident.responder.added",
                            "incident.responder.replied",
                            "incident.status_update_published"
                          ],
                          "priorities": [
                            "ABCDEF1",
                            "AB1CDE2"
                          ],
                          "urgency": null
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      },
      "put": {
        "tags": [
          "Slack Connections"
        ],
        "servers": [
          {
            "url": "https://app.pagerduty.com/integration-slack"
          }
        ],
        "summary": "Update a Slack Connection",
        "description": "Update an existing Slack Connection.",
        "operationId": "updateConnection",
        "parameters": [
          {
            "$ref": "#/components/parameters/slack_team_id"
          },
          {
            "$ref": "#/components/parameters/connection_id"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "slack_connection": {
                    "$ref": "#/components/schemas/SlackConnection"
                  }
                },
                "required": [
                  "slack_connection"
                ]
              },
              "examples": {
                "Request": {
                  "summary": "Request Example",
                  "value": {
                    "slack_connection": {
                      "source_id": "A1234B5",
                      "source_type": "team_reference",
                      "channel_id": "A123B456C7D",
                      "notification_type": "responder",
                      "config": {
                        "events": [
                          "incident.triggered",
                          "incident.acknowledged",
                          "incident.escalated",
                          "incident.resolved",
                          "incident.reassigned",
                          "incident.annotated",
                          "incident.unacknowledged",
                          "incident.delegated",
                          "incident.priority_updated",
                          "incident.responder.added",
                          "incident.responder.replied",
                          "incident.status_update_published"
                        ],
                        "priorities": [
                          "ABCDEF1",
                          "AB1CDE2"
                        ],
                        "urgency": null
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Returns updated Slack Connection.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "slack_connection": {
                      "$ref": "#/components/schemas/SlackConnection"
                    }
                  },
                  "required": [
                    "slack_connection"
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "slack_connection": {
                        "id": "A12BCDE",
                        "source_id": "A1234B5",
                        "source_name": "test_team",
                        "source_type": "team_reference",
                        "channel_id": "A123B456C7D",
                        "channel_name": "random",
                        "notification_type": "responder",
                        "config": {
                          "events": [
                            "incident.triggered",
                            "incident.acknowledged",
                            "incident.escalated",
                            "incident.resolved",
                            "incident.reassigned",
                            "incident.annotated",
                            "incident.unacknowledged",
                            "incident.delegated",
                            "incident.priority_updated",
                            "incident.responder.added",
                            "incident.responder.replied",
                            "incident.status_update_published"
                          ],
                          "priorities": [
                            "ABCDEF1",
                            "AB1CDE2"
                          ],
                          "urgency": null
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      },
      "delete": {
        "tags": [
          "Slack Connections"
        ],
        "servers": [
          {
            "url": "https://app.pagerduty.com/integration-slack"
          }
        ],
        "summary": "Delete a Slack Connection",
        "description": "Delete an existing Slack Connection.",
        "operationId": "deleteConnection",
        "parameters": [
          {
            "$ref": "#/components/parameters/slack_team_id"
          },
          {
            "$ref": "#/components/parameters/connection_id"
          }
        ],
        "responses": {
          "204": {
            "description": "The Slack Connection was deleted successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "slack_connection": {
                      "$ref": "#/components/schemas/SlackConnection"
                    }
                  },
                  "required": [
                    "slack_connection"
                  ]
                },
                "examples": {
                  "Response": {
                    "summary": "Response Example",
                    "value": {
                      "slack_connection": {
                        "id": "A12BCDE",
                        "source_id": "A1234B5",
                        "source_name": "test_team",
                        "source_type": "team_reference",
                        "channel_id": "A123B456C7D",
                        "channel_name": "random",
                        "notification_type": "responder",
                        "config": {
                          "events": [
                            "incident.triggered",
                            "incident.acknowledged",
                            "incident.escalated",
                            "incident.resolved",
                            "incident.reassigned",
                            "incident.annotated",
                            "incident.unacknowledged",
                            "incident.delegated",
                            "incident.priority_updated",
                            "incident.responder.added",
                            "incident.responder.replied",
                            "incident.status_update_published"
                          ],
                          "priorities": [
                            "ABCDEF1",
                            "AB1CDE2"
                          ],
                          "urgency": null
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      }
    }
  },
  "components": {
    "responses": {
      "BadRequest": {
        "description": "Caller provided invalid arguments. Retrying with the same arguments will *not* work.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            },
            "examples": {
              "InvalidInputProvided": {
                "summary": "Invalid payload provided",
                "value": {
                  "error": {
                    "message": "The payload is invalid."
                  }
                }
              }
            }
          }
        }
      },
      "Forbidden": {
        "description": "Caller is not authorized to view the requested resource.\nWhile your authentication is valid, the authenticated user or token does not have permission to perform this action.\n",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            },
            "examples": {
              "AuthorizationError": {
                "summary": "Forbidden",
                "value": {
                  "error": {
                    "message": "Forbidden"
                  }
                }
              }
            }
          }
        }
      },
      "Unauthorized": {
        "description": "Caller did not supply credentials or did not provide the correct credentials.\nIf you are using an API key, it may be invalid or your Authorization header may be malformed.\n",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            },
            "examples": {
              "AuthorizationError": {
                "summary": "Unauthorized",
                "value": {
                  "error": {
                    "message": "Unauthorized"
                  }
                }
              }
            }
          }
        }
      },
      "NotFound": {
        "description": "The requested resource was not found.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            },
            "examples": {
              "NotFound": {
                "summary": "Not Found",
                "value": {
                  "error": {
                    "message": "Not Found"
                  }
                }
              },
              "InvalidWorkspace": {
                "summary": "Invalid Workspace",
                "value": {
                  "error": {
                    "message": "The PagerDuty has not been connected to this workspace. Please complete the installation and try again."
                  }
                }
              }
            }
          }
        }
      },
      "UnprocessableEntity": {
        "description": "The request could not be performed successfully, because some validations failed.\n",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            },
            "examples": {
              "AuthorizationError": {
                "summary": "UnprocessableEntity",
                "value": {
                  "error": {
                    "message": "UnprocessableEntity"
                  }
                }
              }
            }
          }
        }
      },
      "InternalServerError": {
        "description": "Request resulted in internal server error.\n",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            },
            "examples": {
              "InternalServerError": {
                "summary": "Internal Server Error",
                "value": {
                  "error": {
                    "message": "Internal Server Error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "schemas": {
      "SlackChannel": {
        "title": "Slack Channel",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "slack_team_id": {
            "type": "string"
          },
          "link": {
            "type": "string"
          },
          "deep_link": {
            "type": "string"
          }
        }
      },
      "CreateDedicatedChannelPayload": {
        "title": "Create Dedicated Channel Payload",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "slack_team_id": {
            "type": "string"
          },
          "privacy": {
            "type": "string",
            "enum": [
              "private",
              "public"
            ]
          }
        }
      },
      "CreateNotificationChannelPayload": {
        "title": "Create Notification Channel Payload",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "slack_team_id": {
            "type": "string"
          }
        }
      },
      "UpdateNotificationChannelPayload": {
        "title": "Update Notification Channel Payload",
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "slack_team_id": {
              "type": "string"
            }
          }
        }
      },
      "SlackConnection": {
        "title": "Slack Connection",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "source_id": {
            "type": "string"
          },
          "source_name": {
            "type": "string"
          },
          "source_type": {
            "$ref": "#/components/schemas/SlackConnectionSourceType"
          },
          "channel_id": {
            "type": "string"
          },
          "channel_name": {
            "type": "string"
          },
          "notification_type": {
            "$ref": "#/components/schemas/SlackConnectionNotifiationType"
          },
          "config": {
            "$ref": "#/components/schemas/SlackConnectionConfig"
          }
        }
      },
      "SlackConnectionNotifiationType": {
        "title": "Slack Connection Notification Type",
        "default": "responder",
        "description": "Configuration item of the Slack connection that indicates how Slack message will be formatted (can be `responder` or `stakeholder`)",
        "type": "string",
        "enum": [
          "responder",
          "stakeholder"
        ]
      },
      "SlackConnectionSourceType": {
        "title": "Slack Connection Source Type",
        "description": "Configuration item of the Slack connection that indicates what PagerDuty source would be used for the connection (can be Service or Team).",
        "type": "string",
        "enum": [
          "service_reference",
          "team_reference"
        ]
      },
      "SlackConnectionConfig": {
        "title": "Slack Connection Config",
        "description": "Item of the Slack connection that contains configuration options (filters).",
        "type": "object",
        "properties": {
          "events": {
            "$ref": "#/components/schemas/SlackConnectionEvents"
          },
          "urgency": {
            "$ref": "#/components/schemas/SlackConnectionUrgency"
          },
          "priorities": {
            "$ref": "#/components/schemas/SlackConnectionPriorities"
          }
        }
      },
      "SlackConnectionUrgency": {
        "title": "Slack Connection Urgency",
        "description": "Configuration item of the Slack connection allows you to filter events by urgency.",
        "type": "string",
        "nullable": true,
        "enum": [
          "high",
          "low",
          null
        ]
      },
      "SlackConnectionEvents": {
        "title": "Slack Connection Events",
        "description": "Configuration item of the Slack connection allows you to subscribe to different type of events.",
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "incident.acknowledged",
            "incident.annotated",
            "incident.delegated",
            "incident.escalated",
            "incident.priority_updated",
            "incident.reassigned",
            "incident.resolved",
            "incident.triggered",
            "incident.unacknowledged",
            "incident.responder.added",
            "incident.responder.replied",
            "incident.status_update_published"
          ]
        }
      },
      "SlackConnectionPriorities": {
        "title": "Slack Connection Priorities",
        "description": "Configuration item of the Slack connection that allows you to filter events by priorities. If set to 'null', the connection accepts events of any priority, including those without a specified priority. If set to an empty array, only events without a specific priority are allowed. Otherwise, event filtering adheres to the specific priority codes provided in the array, and the special code 'no_priority' can also be included in the array.",
        "nullable": true,
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "error": {
            "type": "object",
            "properties": {
              "message": {
                "type": "string",
                "readOnly": true,
                "description": "Error message string.",
                "example": "Invalid Input Provided"
              }
            },
            "required": [
              "message"
            ]
          }
        },
        "required": [
          "error"
        ]
      },
      "Pagination": {
        "type": "object",
        "properties": {
          "offset": {
            "type": "integer",
            "description": "Echoes offset pagination property.",
            "readOnly": true,
            "default": 0
          },
          "limit": {
            "type": "integer",
            "description": "Echoes limit pagination property.",
            "readOnly": true,
            "minimum": 0,
            "maximum": 100,
            "default": 50
          },
          "more": {
            "type": "boolean",
            "description": "Indicates if there are additional records to return.",
            "readOnly": true,
            "default": false
          },
          "total": {
            "type": "integer",
            "description": "The total number of records matching the given query.",
            "nullable": false,
            "readOnly": true,
            "default": null
          }
        },
        "required": [
          "offset",
          "limit",
          "more",
          "total"
        ]
      }
    },
    "securitySchemes": {
      "apiKey": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header",
        "description": "The API Key with format `Token token=<API_KEY>`"
      },
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "The Bearer access token with format `Bearer <BEARER TOKEN>`"
      }
    },
    "parameters": {
      "incident_id": {
        "name": "incident_id",
        "description": "PagerDuty Incident ID.",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "channel_id": {
        "name": "channel_id",
        "description": "Slack Channel ID.",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "connection_id": {
        "name": "connection_id",
        "description": "Slack connection id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "slack_team_id": {
        "name": "slack_team_id",
        "description": "Slack team (workspace) id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "limit": {
        "name": "limit",
        "in": "query",
        "description": "Set the maximum number of results matched by the query.",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100,
          "default": 50
        }
      },
      "offset": {
        "name": "offset",
        "in": "query",
        "description": "The number of items to skip before starting to collect the result set.",
        "schema": {
          "type": "integer",
          "minimum": 0,
          "default": 0
        }
      }
    }
  }
}